import { useQuery } from "@tanstack/react-query";
import { AlertTriangle, HelpCircle, Sparkles, Wand2, X } from "lucide-react";
import React, { useEffect, useRef, useState } from "react";

import { getMetadata } from "../../../services/card";
import { generateAiDeck, getFormats } from "../../../services/deck";
import type { DeckCardItem } from "../../../types";
import Button from "../../ui/Button";
import Label from "../../ui/Label";
import Select from "../../ui/Select";
import Textarea from "../../ui/Textarea";
import ArchetypeAutocomplete from "./ArchetypeAutocomplete";
import StrategySelector from "./StrategySelector";
import WizardLoading from "./WizardLoading";
import WizardWarnings from "./WizardWarnings";

/**
 * Props for the {@link AiDeckWizard} component.
 */
export interface AiDeckWizardProps {
  isOpen: boolean;
  onClose: () => void;
  onDeckGenerated: (generatedData: {
    name: string;
    description: string;
    formatName: string;
    deckCards: DeckCardItem[];
  }) => void;
  currentFormat: string;
}

/**
 * AiDeckWizard is a modal dialog flow utilizing AI to generate a functional
 * Yu-Gi-Oh! deck list based on archetype search, strategic goals (e.g., aggro, control),
 * format restrictions, and user-specified custom prompts.
 *
 * @param props - The component props.
 * @returns The rendered AiDeckWizard dialog element.
 */
export default function AiDeckWizard({
  isOpen,
  onClose,
  onDeckGenerated,
  currentFormat,
}: AiDeckWizardProps) {
  const [archetype, setArchetype] = useState("");
  const [strategy, setStrategy] = useState("None");
  const [formatName, setFormatName] = useState(currentFormat || "TCG");
  const [customPrompt, setCustomPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string>();
  const [warnings, setWarnings] = useState<string[]>([]);
  const dialogRef = useRef<HTMLDialogElement>(null);

  const { data: archetypesData } = useQuery<string[]>({
    queryKey: ["metadata", "archetypes"],
    queryFn: ({ signal }) => getMetadata("archetypes", signal),
  });
  const { data: formatsData } = useQuery<string[]>({
    queryKey: ["formats"],
    queryFn: ({ signal }) => getFormats(signal),
  });
  const formats = formatsData || ["TCG", "OCG", "Goat", "Edison"];

  const [prevIsOpen, setPrevIsOpen] = useState(isOpen);
  const [prevCurrentFormat, setPrevCurrentFormat] = useState(currentFormat);

  if (isOpen !== prevIsOpen || currentFormat !== prevCurrentFormat) {
    setPrevIsOpen(isOpen);
    setPrevCurrentFormat(currentFormat);
    if (isOpen) {
      setLoading(false);
      setError(undefined);
      setWarnings([]);
      setArchetype("");
      setStrategy("None");
      setCustomPrompt("");
      setFormatName(currentFormat || "TCG");
    }
  }

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    if (isOpen) {
      if (!dialog.open) {
        dialog.showModal();
      }
    } else {
      if (dialog.open) {
        dialog.close();
      }
    }
  }, [isOpen]);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    const handleClose = () => {
      onClose();
    };

    dialog.addEventListener("close", handleClose);
    return () => {
      dialog.removeEventListener("close", handleClose);
    };
  }, [onClose]);

  const handleGenerate = async (e: React.SubmitEvent) => {
    e.preventDefault();
    if (!archetype.trim()) {
      setError("Please specify an archetype first.");
      return;
    }

    setLoading(true);
    setError(undefined);
    setWarnings([]);

    try {
      const result = await generateAiDeck({
        archetype: archetype.trim(),
        strategy,
        formatName,
        customPrompt: customPrompt.trim(),
      });

      onDeckGenerated({
        name: result.name || `${archetype} Deck`,
        description: result.description || "Generated by DeckLab.",
        formatName: result.formatName || formatName,
        deckCards: result.deckCards || [],
      });

      if (result.validationWarnings && result.validationWarnings.length > 0) {
        setWarnings(result.validationWarnings);
        setLoading(false);
      } else {
        dialogRef.current?.close();
      }
    } catch (err) {
      setError(
        err instanceof Error ? err.message : "An unexpected error occurred during generation.",
      );
      setLoading(false);
    }
  };

  const handleBackdropClick = (e: React.MouseEvent<HTMLDialogElement>) => {
    if (e.target === dialogRef.current) {
      dialogRef.current?.close();
    }
  };

  return (
    <dialog
      ref={dialogRef}
      onClick={handleBackdropClick}
      className="max-h-[90vh] w-full max-w-lg overflow-visible border-none bg-transparent p-4 text-white backdrop:bg-black/75 backdrop:backdrop-blur-sm focus:outline-none"
    >
      <div className="bg-dark-surface border-border-dim relative flex max-h-[85vh] flex-col overflow-y-auto rounded-2xl border p-6 shadow-2xl">
        <div className="border-border-dim mb-4 flex items-center justify-between border-b pb-4">
          <div className="flex items-center gap-2">
            <Sparkles className="text-gold-accent h-5 w-5" />
            <h2 className="text-lg font-bold text-slate-100">AI Deck Generator Wizard</h2>
          </div>
          <button
            type="button"
            className="cursor-pointer text-slate-400 transition-colors hover:text-white"
            disabled={loading}
            onClick={() => dialogRef.current?.close()}
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {error && (
          <div className="mb-4 flex items-start gap-2 rounded-xl border border-red-800/60 bg-red-950/40 p-3 text-xs text-red-200">
            <AlertTriangle className="h-4 w-4 shrink-0 text-red-500" />
            <span>{error}</span>
          </div>
        )}

        {warnings.length > 0 && <WizardWarnings warnings={warnings} onClose={onClose} />}

        {loading ? (
          <WizardLoading />
        ) : (
          !warnings.length && (
            <form onSubmit={handleGenerate} className="flex-1 space-y-4">
              <ArchetypeAutocomplete
                value={archetype}
                onChange={setArchetype}
                disabled={loading}
                archetypes={archetypesData || []}
              />

              <div>
                <Label htmlFor="format">Format rules</Label>
                <Select
                  id="format"
                  value={formatName}
                  onChange={(e) => setFormatName(e.target.value)}
                  disabled={loading}
                  className="mt-1"
                >
                  {formats.map((f) => (
                    <option key={f} value={f}>
                      {f}
                    </option>
                  ))}
                </Select>
              </div>

              <StrategySelector value={strategy} onChange={setStrategy} disabled={loading} />

              <div>
                <div className="mb-1 flex items-center gap-1.5">
                  <Label htmlFor="customPrompt" className="mb-0">
                    Custom Rules / Instructions (Optional)
                  </Label>
                  <div className="group relative">
                    <HelpCircle className="h-3.5 w-3.5 cursor-help text-slate-400" />
                    <div className="bg-dark-surface-elevated border-border-dim absolute bottom-full left-1/2 mb-1 hidden w-48 -translate-x-1/2 rounded border px-2 py-1 text-center text-[10px] leading-normal text-slate-300 shadow-lg group-hover:block">
                      Specify specific cards to include, budget options, or combo focuses.
                    </div>
                  </div>
                </div>
                <Textarea
                  id="customPrompt"
                  value={customPrompt}
                  onChange={(e) => setCustomPrompt(e.target.value)}
                  placeholder="e.g. Include Gorz, don't use traps, focus on milling..."
                  disabled={loading}
                  className="h-20 resize-none"
                />
              </div>

              <div className="flex gap-3 pt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => dialogRef.current?.close()}
                  disabled={loading}
                  className="flex-1"
                >
                  Cancel
                </Button>
                <Button type="submit" isLoading={loading} className="flex-1">
                  <Wand2 className="h-4 w-4" />
                  Generate Deck
                </Button>
              </div>
            </form>
          )
        )}
      </div>
    </dialog>
  );
}
