import { AlertTriangle, HelpCircle, Sparkles, Wand2, X } from "lucide-react";
import React, { useEffect, useRef, useState } from "react";
import { useFetch } from "../../../hooks/useFetch";
import { getCardMetadataEndpoint } from "../../../services/card";
import { generateAiDeck, getFormatsEndpoint } from "../../../services/deck";
import type { DeckCardItem } from "../../../types";
import Button from "../../ui/Button";
import Label from "../../ui/Label";
import Select from "../../ui/Select";
import Textarea from "../../ui/Textarea";
import ArchetypeAutocomplete from "./ArchetypeAutocomplete";
import StrategySelector from "./StrategySelector";
import WizardLoading from "./WizardLoading";
import WizardWarnings from "./WizardWarnings";

export interface AiDeckWizardProps {
  isOpen: boolean;
  onClose: () => void;
  onDeckGenerated: (generatedData: {
    name: string;
    description: string;
    formatName: string;
    deckCards: DeckCardItem[];
  }) => void;
  currentFormat: string;
}

export default function AiDeckWizard({
  isOpen,
  onClose,
  onDeckGenerated,
  currentFormat,
}: AiDeckWizardProps) {
  const [archetype, setArchetype] = useState("");
  const [strategy, setStrategy] = useState("None");
  const [formatName, setFormatName] = useState(currentFormat || "TCG");
  const [customPrompt, setCustomPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [warnings, setWarnings] = useState<string[]>([]);
  const dialogRef = useRef<HTMLDialogElement>(null);

  const { data: archetypesData } = useFetch<string[]>(getCardMetadataEndpoint("archetypes"));
  const { data: formatsData } = useFetch<string[]>(getFormatsEndpoint());
  const formats = formatsData || ["TCG", "OCG", "Goat", "Edison"];

  useEffect(() => {
    if (isOpen) {
      setLoading(false);
      setError(null);
      setWarnings([]);
      setArchetype("");
      setStrategy("None");
      setCustomPrompt("");
      setFormatName(currentFormat || "TCG");
    }
  }, [isOpen, currentFormat]);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    if (isOpen) {
      if (!dialog.open) {
        dialog.showModal();
      }
    } else {
      if (dialog.open) {
        dialog.close();
      }
    }
  }, [isOpen]);

  useEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;

    const handleClose = () => {
      onClose();
    };

    dialog.addEventListener("close", handleClose);
    return () => {
      dialog.removeEventListener("close", handleClose);
    };
  }, [onClose]);

  const handleGenerate = async (e: React.SubmitEvent) => {
    e.preventDefault();
    if (!archetype.trim()) {
      setError("Please specify an archetype first.");
      return;
    }

    setLoading(true);
    setError(null);
    setWarnings([]);

    try {
      const result = await generateAiDeck({
        archetype: archetype.trim(),
        strategy,
        formatName,
        customPrompt: customPrompt.trim() || null,
      });

      onDeckGenerated({
        name: result.name || `${archetype} Deck`,
        description: result.description || "Generated by DeckLab.",
        formatName: result.formatName || formatName,
        deckCards: result.deckCards || [],
      });

      if (result.validationWarnings && result.validationWarnings.length > 0) {
        setWarnings(result.validationWarnings);
        setLoading(false);
      } else {
        dialogRef.current?.close();
      }
    } catch (err: any) {
      setError(err.message || "An unexpected error occurred during generation.");
      setLoading(false);
    }
  };

  return (
    <dialog
      ref={dialogRef}
      className="bg-transparent text-white p-4 border-none backdrop:bg-black/75 backdrop:backdrop-blur-sm focus:outline-none max-w-lg w-full max-h-[90vh] overflow-visible"
    >
      <div className="bg-dark-surface border border-border-dim rounded-2xl p-6 shadow-2xl relative flex flex-col max-h-[85vh] overflow-y-auto">
        <div className="flex items-center justify-between pb-4 border-b border-border-dim mb-4">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-gold-accent animate-pulse" />
            <h2 className="text-lg font-bold text-slate-100">AI Deck Generator Wizard</h2>
          </div>
          <button
            type="button"
            className="text-slate-400 hover:text-white transition-colors cursor-pointer"
            disabled={loading}
            onClick={() => dialogRef.current?.close()}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {error && (
          <div className="mb-4 p-3 bg-red-950/40 border border-red-800/60 rounded-xl text-red-200 text-xs flex gap-2 items-start">
            <AlertTriangle className="w-4 h-4 shrink-0 text-red-500" />
            <span>{error}</span>
          </div>
        )}

        {warnings.length > 0 && <WizardWarnings warnings={warnings} onClose={onClose} />}

        {loading ? (
          <WizardLoading />
        ) : (
          !warnings.length && (
            <form onSubmit={handleGenerate} className="space-y-4 flex-1">
              <ArchetypeAutocomplete
                value={archetype}
                onChange={setArchetype}
                disabled={loading}
                archetypes={archetypesData || []}
              />

              <div>
                <Label htmlFor="format">Format rules</Label>
                <Select
                  id="format"
                  value={formatName}
                  onChange={(e) => setFormatName(e.target.value)}
                  disabled={loading}
                  className="mt-1"
                >
                  {formats.map((f) => (
                    <option key={f} value={f}>
                      {f}
                    </option>
                  ))}
                </Select>
              </div>

              <StrategySelector value={strategy} onChange={setStrategy} disabled={loading} />

              <div>
                <div className="flex items-center gap-1.5 mb-1">
                  <Label htmlFor="customPrompt" className="mb-0">
                    Custom Rules / Instructions (Optional)
                  </Label>
                  <div className="relative group">
                    <HelpCircle className="w-3.5 h-3.5 text-slate-400 cursor-help" />
                    <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1 hidden group-hover:block bg-dark-surface-elevated border border-border-dim rounded px-2 py-1 text-[10px] text-slate-300 w-48 shadow-lg text-center leading-normal">
                      Specify specific cards to include, budget options, or combo focuses.
                    </div>
                  </div>
                </div>
                <Textarea
                  id="customPrompt"
                  value={customPrompt}
                  onChange={(e) => setCustomPrompt(e.target.value)}
                  placeholder="e.g. Include Gorz, don't use traps, focus on milling..."
                  disabled={loading}
                  className="resize-none h-20"
                />
              </div>

              <div className="flex gap-3 pt-2">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => dialogRef.current?.close()}
                  disabled={loading}
                  className="flex-1"
                >
                  Cancel
                </Button>
                <Button type="submit" isLoading={loading} className="flex-1">
                  <Wand2 className="w-4 h-4" />
                  Generate Deck
                </Button>
              </div>
            </form>
          )
        )}
      </div>
    </dialog>
  );
}
