package com.deck.lab.backend.service;

import java.util.ArrayList;
import java.util.List;

import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.deck.lab.backend.dto.request.DeckGenerateRequestDto;
import com.deck.lab.backend.dto.request.DeckSuggestRequestDto;
import com.deck.lab.backend.dto.response.CardSuggestionResponseDto;
import com.deck.lab.backend.dto.response.CardSuggestionListResponseDto;
import com.deck.lab.backend.dto.response.DeckCardResponseDto;
import com.deck.lab.backend.dto.response.DeckGenerationResponseDto;
import com.deck.lab.backend.model.Deck;
import com.deck.lab.backend.service.generation.AiClient;
import com.deck.lab.backend.service.generation.model.CardEntry;
import com.deck.lab.backend.service.generation.CardResolver;
import com.deck.lab.backend.service.generation.DeckAssembler;
import com.deck.lab.backend.service.generation.model.DeckGenerateAiResponse;
import com.deck.lab.backend.service.generation.PromptBuilder;
import com.deck.lab.backend.service.generation.model.ResolvedCardEntry;
import com.deck.lab.backend.service.generation.ResponseParser;
import com.deck.lab.backend.service.generation.ValidationAdapter;

/**
 * Service managing AI-driven deck generation and card synergy recommendations.
 * Orchestrates calls using the deep AI generation sub-modules.
 */
@Service
public class GenerationService {

        private final PromptBuilder promptBuilder;
        private final AiClient aiClient;
        private final ResponseParser responseParser;
        private final CardResolver cardResolver;
        private final DeckAssembler deckAssembler;
        private final ValidationAdapter validationAdapter;

        public GenerationService(PromptBuilder promptBuilder,
                        AiClient aiClient,
                        ResponseParser responseParser,
                        CardResolver cardResolver,
                        DeckAssembler deckAssembler,
                        ValidationAdapter validationAdapter) {
                this.promptBuilder = promptBuilder;
                this.aiClient = aiClient;
                this.responseParser = responseParser;
                this.cardResolver = cardResolver;
                this.deckAssembler = deckAssembler;
                this.validationAdapter = validationAdapter;
        }

        /**
         * Generates a complete, legally compliant deck list using an iterative
         * refinement loop.
         *
         * <p>
         * The process runs as follows:
         * </p>
         * <ol>
         * <li>First, a draft deck is generated by the LLM.</li>
         * <li>The draft card list is resolved against the database and format
         * rules.</li>
         * <li>If any unresolved card names or validation warnings exist, the service
         * enters a refinement loop (up to 5 steps) and prompts the LLM again, feeding
         * back the specific errors to resolve.</li>
         * <li>The loop terminates early if the deck is fully resolved and
         * compliant.</li>
         * </ol>
         *
         * @param request the DTO parameters specifying archetype, strategy, and format
         *                rules
         * @return the finalized deck list, matching database cards, and any validation
         *         warnings
         */
        @Transactional(readOnly = true)
        public DeckGenerationResponseDto generateDeck(DeckGenerateRequestDto request) {
                BeanOutputConverter<DeckGenerateAiResponse> converter = new BeanOutputConverter<>(
                                DeckGenerateAiResponse.class);

                Prompt draftPrompt = promptBuilder.buildDraftPrompt(request, converter.getFormat());
                String responseContent = aiClient.call(draftPrompt);
                DeckGenerateAiResponse aiDeck = responseParser.parseGenerationResponse(responseContent);

                String deckName = aiDeck != null && aiDeck.getName() != null && !aiDeck.getName().isBlank()
                                ? aiDeck.getName()
                                : request.getArchetype() + " Deck";

                List<ResolvedCardEntry> resolved = cardResolver.resolveCards(
                                aiDeck != null ? aiDeck.getCards() : List.of());
                List<String> unresolvedNames = getUnresolvedNames(aiDeck != null ? aiDeck.getCards() : List.of());
                List<String> warnings = getValidationWarnings(request, resolved, deckName);

                int step = 1;
                int maxSteps = 5;
                while ((!unresolvedNames.isEmpty() || !warnings.isEmpty()) && step < maxSteps) {
                        step++;
                        Prompt refinementPrompt = promptBuilder.buildRefinementPrompt(
                                        request,
                                        resolved,
                                        unresolvedNames,
                                        warnings,
                                        converter.getFormat());
                        responseContent = aiClient.call(refinementPrompt);
                        aiDeck = responseParser.parseGenerationResponse(responseContent);
                        if (aiDeck == null) {
                                break;
                        }
                        if (aiDeck.getName() != null && !aiDeck.getName().isBlank()) {
                                deckName = aiDeck.getName();
                        }
                        resolved = cardResolver.resolveCards(aiDeck.getCards());
                        unresolvedNames = getUnresolvedNames(aiDeck.getCards());
                        warnings = getValidationWarnings(request, resolved, deckName);
                }

                List<DeckCardResponseDto> matchedCards = deckAssembler.toDeckCardDtos(resolved);

                String description = aiDeck != null && aiDeck.getDescription() != null
                                ? aiDeck.getDescription()
                                : "AI generated deck.";

                return new DeckGenerationResponseDto(
                                deckName,
                                description.length() > 255
                                                ? description.substring(0, 255)
                                                : description,
                                request.getFormatName(),
                                matchedCards,
                                warnings);
        }

        /**
         * Identifies which card names suggested by the LLM are unrecognized by the
         * database.
         *
         * @param cards the list of card entries suggested in the AI response
         * @return a list of unrecognized card names
         */
        private List<String> getUnresolvedNames(List<CardEntry> cards) {
                List<String> unresolved = new ArrayList<>();
                if (cards == null) {
                        return unresolved;
                }
                for (CardEntry entry : cards) {
                        if (entry.getName() == null || entry.getName().isBlank()) {
                                continue;
                        }
                        if (cardResolver.lookupCard(entry.getName()).isEmpty()) {
                                unresolved.add(entry.getName());
                        }
                }
                return unresolved;
        }

        /**
         * Assembles a temporary deck and runs format legality validation checks.
         *
         * @param request  the generation parameters containing format and strategy
         *                 rules
         * @param resolved the list of database-resolved card entries
         * @param deckName the name assigned to the deck
         * @return a list of human-readable format validation error messages
         */
        private List<String> getValidationWarnings(DeckGenerateRequestDto request,
                        List<ResolvedCardEntry> resolved, String deckName) {
                Deck deck = deckAssembler.assembleDeck(deckName, request.getFormatName(), resolved);
                return validationAdapter.validate(deck);
        }

        /**
         * Provides exactly 5 card recommendations that synergize with the current deck
         * list.
         *
         * @param request the DTO containing the current deck list and target format
         *                name
         * @return a list of 5 card suggestions with synergy rationales
         */
        @Transactional(readOnly = true)
        public List<CardSuggestionResponseDto> suggestCards(DeckSuggestRequestDto request) {
                BeanOutputConverter<CardSuggestionListResponseDto> converter = new BeanOutputConverter<>(
                                CardSuggestionListResponseDto.class);

                Prompt prompt = promptBuilder.buildSuggestionPrompt(request, converter.getFormat());
                String responseContent = aiClient.call(prompt);
                CardSuggestionListResponseDto aiSuggestions = responseParser.parseSuggestionResponse(responseContent);

                return cardResolver.resolveSuggestions(
                                aiSuggestions != null
                                                ? aiSuggestions.getSuggestions()
                                                : List.of());
        }
}
