package com.deck.lab.backend.dto;

/**
 * Data Transfer Object (DTO) conveying card suggestions recommended by AI
 * models.
 *
 * <p>
 * <strong>Data Transfer Object (DTO)</strong>
 * </p>
 * <p>
 * This class encapsulates the response payload returned to clients when
 * requesting AI-based card suggestions. It is a hybrid model that combines
 * unmapped details generated by LLM analysis (such as {@code synergyReason})
 * with formal card attributes retrieved from the database (such as
 * {@code cardId}, {@code type}, and {@code imageUrl}).
 * </p>
 *
 * <p>
 * By separating the suggestion representation from both the raw AI response and
 * the strict JPA entity representation, we keep the controller response
 * contract decoupled from internal database schema details while enriching the
 * AI data with actual database records.
 * </p>
 */
public class CardSuggestionDto {

    private String name;

    /**
     * Suggested deck section placement (e.g. MAIN, EXTRA, SIDE).
     */
    private String section;

    /**
     * Architectural explanation generated by AI detailing card synergies.
     */
    private String synergyReason;

    /**
     * Database-resolved Card ID primary key.
     */
    private Long cardId;

    /**
     * Card classification category type.
     */
    private String type;

    private String imageUrl;

    public CardSuggestionDto() {
    }

    public CardSuggestionDto(String name, String section, String synergyReason) {
        this.name = name;
        this.section = section;
        this.synergyReason = synergyReason;
    }

    public CardSuggestionDto(String name, String section, String synergyReason, Long cardId, String type,
            String imageUrl) {
        this.name = name;
        this.section = section;
        this.synergyReason = synergyReason;
        this.cardId = cardId;
        this.type = type;
        this.imageUrl = imageUrl;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public String getSynergyReason() {
        return synergyReason;
    }

    public void setSynergyReason(String synergyReason) {
        this.synergyReason = synergyReason;
    }

    public Long getCardId() {
        return cardId;
    }

    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
}
