package com.deck.lab.backend.service.generation;

import org.springframework.ai.converter.BeanOutputConverter;
import org.springframework.stereotype.Component;

import com.deck.lab.backend.dto.response.CardSuggestionListResponseDto;
import com.deck.lab.backend.service.generation.model.DeckGenerateAiResponse;

/**
 * Pure parsing component that converts string responses from AI into structured
 * objects.
 */
@Component
public class ResponseParser {

    /**
     * Parses the raw AI text response into a structured deck generation DTO.
     *
     * @param rawResponse the raw text generated by the AI
     * @return the parsed DeckGenerateAiResponseDto object
     */
    public DeckGenerateAiResponse parseGenerationResponse(String rawResponse) {
        BeanOutputConverter<DeckGenerateAiResponse> converter = new BeanOutputConverter<>(
                DeckGenerateAiResponse.class);
        return converter.convert(rawResponse);
    }

    /**
     * Parses the raw AI text response into a structured card suggestions DTO.
     *
     * @param rawResponse the raw text generated by the AI
     * @return the parsed CardSuggestionsAiResponseDto object
     */
    public CardSuggestionListResponseDto parseSuggestionResponse(String rawResponse) {
        BeanOutputConverter<CardSuggestionListResponseDto> converter = new BeanOutputConverter<>(
                CardSuggestionListResponseDto.class);
        return converter.convert(rawResponse);
    }
}
