package com.deck.lab.backend.service.generation.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Data Transfer Object (DTO) capturing the raw AI-generated deck payload
 * structure.
 *
 * <p>
 * <strong>Response DTO</strong>
 * </p>
 * <p>
 * This object serves as a structured bridge between the unstructured text
 * output generated by the LLM and our application's domain services. It
 * provides standard fields (name, description, and list of card entries) that
 * our parsing service extracts from the raw LLM responses before we query the
 * database to validate and resolve actual cards.
 * </p>
 */
public class DeckGenerateAiResponse {
    private String name;
    private String description;
    private List<CardEntry> cards = new ArrayList<>();

    public DeckGenerateAiResponse() {
    }

    public DeckGenerateAiResponse(String name, String description, List<CardEntry> cards) {
        this.name = name;
        this.description = description;
        this.cards = cards;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<CardEntry> getCards() {
        return cards;
    }

    public void setCards(List<CardEntry> cards) {
        this.cards = cards;
    }
}
