// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/unit/deck_builder_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mobile/domain/enums/enums.dart' as _i10;
import 'package:mobile/domain/models/card.dart' as _i6;
import 'package:mobile/domain/models/card_suggestion.dart' as _i12;
import 'package:mobile/domain/models/deck_card.dart' as _i11;
import 'package:mobile/domain/models/deck_detail.dart' as _i3;
import 'package:mobile/domain/models/deck_generation.dart' as _i5;
import 'package:mobile/domain/models/deck_summary.dart' as _i9;
import 'package:mobile/domain/models/deck_validation.dart' as _i4;
import 'package:mobile/domain/models/page.dart' as _i2;
import 'package:mobile/domain/repositories/card_repository.dart' as _i13;
import 'package:mobile/domain/repositories/deck_repository.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePage_0<T> extends _i1.SmartFake implements _i2.Page<T> {
  _FakePage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeckDetail_1 extends _i1.SmartFake implements _i3.DeckDetail {
  _FakeDeckDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeckValidation_2 extends _i1.SmartFake
    implements _i4.DeckValidation {
  _FakeDeckValidation_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeckGeneration_3 extends _i1.SmartFake
    implements _i5.DeckGeneration {
  _FakeDeckGeneration_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCard_4 extends _i1.SmartFake implements _i6.Card {
  _FakeCard_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DeckRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeckRepository extends _i1.Mock implements _i7.DeckRepository {
  @override
  _i8.Future<_i2.Page<_i9.DeckSummary>> fetchPublicDecks({
    String? name,
    String? format,
    String? username,
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPublicDecks, [], {
              #name: name,
              #format: format,
              #username: username,
              #page: page,
              #size: size,
            }),
            returnValue: _i8.Future<_i2.Page<_i9.DeckSummary>>.value(
              _FakePage_0<_i9.DeckSummary>(
                this,
                Invocation.method(#fetchPublicDecks, [], {
                  #name: name,
                  #format: format,
                  #username: username,
                  #page: page,
                  #size: size,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.Page<_i9.DeckSummary>>.value(
                  _FakePage_0<_i9.DeckSummary>(
                    this,
                    Invocation.method(#fetchPublicDecks, [], {
                      #name: name,
                      #format: format,
                      #username: username,
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i2.Page<_i9.DeckSummary>>);

  @override
  _i8.Future<_i2.Page<_i9.DeckSummary>> fetchUserDecks({
    String? name,
    String? format,
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserDecks, [], {
              #name: name,
              #format: format,
              #page: page,
              #size: size,
            }),
            returnValue: _i8.Future<_i2.Page<_i9.DeckSummary>>.value(
              _FakePage_0<_i9.DeckSummary>(
                this,
                Invocation.method(#fetchUserDecks, [], {
                  #name: name,
                  #format: format,
                  #page: page,
                  #size: size,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.Page<_i9.DeckSummary>>.value(
                  _FakePage_0<_i9.DeckSummary>(
                    this,
                    Invocation.method(#fetchUserDecks, [], {
                      #name: name,
                      #format: format,
                      #page: page,
                      #size: size,
                    }),
                  ),
                ),
          )
          as _i8.Future<_i2.Page<_i9.DeckSummary>>);

  @override
  _i8.Future<_i3.DeckDetail> fetchDeckDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDeckDetail, [id]),
            returnValue: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(#fetchDeckDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(#fetchDeckDetail, [id]),
              ),
            ),
          )
          as _i8.Future<_i3.DeckDetail>);

  @override
  _i8.Future<_i3.DeckDetail> createDeck({
    required String? name,
    required String? description,
    required _i10.Format? formatName,
    required List<_i11.DeckCard>? deckCards,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createDeck, [], {
              #name: name,
              #description: description,
              #formatName: formatName,
              #deckCards: deckCards,
            }),
            returnValue: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(#createDeck, [], {
                  #name: name,
                  #description: description,
                  #formatName: formatName,
                  #deckCards: deckCards,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(#createDeck, [], {
                  #name: name,
                  #description: description,
                  #formatName: formatName,
                  #deckCards: deckCards,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.DeckDetail>);

  @override
  _i8.Future<_i3.DeckDetail> updateDeck(
    int? id, {
    required String? name,
    required String? description,
    required _i10.Format? formatName,
    required List<_i11.DeckCard>? deckCards,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateDeck,
              [id],
              {
                #name: name,
                #description: description,
                #formatName: formatName,
                #deckCards: deckCards,
              },
            ),
            returnValue: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(
                  #updateDeck,
                  [id],
                  {
                    #name: name,
                    #description: description,
                    #formatName: formatName,
                    #deckCards: deckCards,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.DeckDetail>.value(
              _FakeDeckDetail_1(
                this,
                Invocation.method(
                  #updateDeck,
                  [id],
                  {
                    #name: name,
                    #description: description,
                    #formatName: formatName,
                    #deckCards: deckCards,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i3.DeckDetail>);

  @override
  _i8.Future<void> deleteDeck(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDeck, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<String>> fetchFormats() =>
      (super.noSuchMethod(
            Invocation.method(#fetchFormats, []),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i4.DeckValidation> validateDeck({
    required String? name,
    required _i10.Format? formatName,
    required List<_i11.DeckCard>? deckCards,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#validateDeck, [], {
              #name: name,
              #formatName: formatName,
              #deckCards: deckCards,
            }),
            returnValue: _i8.Future<_i4.DeckValidation>.value(
              _FakeDeckValidation_2(
                this,
                Invocation.method(#validateDeck, [], {
                  #name: name,
                  #formatName: formatName,
                  #deckCards: deckCards,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.DeckValidation>.value(
              _FakeDeckValidation_2(
                this,
                Invocation.method(#validateDeck, [], {
                  #name: name,
                  #formatName: formatName,
                  #deckCards: deckCards,
                }),
              ),
            ),
          )
          as _i8.Future<_i4.DeckValidation>);

  @override
  _i8.Future<List<_i12.CardSuggestion>> fetchAiSuggestions({
    required _i10.Format? formatName,
    required List<_i11.DeckCard>? currentCards,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAiSuggestions, [], {
              #formatName: formatName,
              #currentCards: currentCards,
            }),
            returnValue: _i8.Future<List<_i12.CardSuggestion>>.value(
              <_i12.CardSuggestion>[],
            ),
            returnValueForMissingStub:
                _i8.Future<List<_i12.CardSuggestion>>.value(
                  <_i12.CardSuggestion>[],
                ),
          )
          as _i8.Future<List<_i12.CardSuggestion>>);

  @override
  _i8.Future<_i5.DeckGeneration> generateAiDeck({
    required String? archetype,
    required _i10.Strategy? strategy,
    required _i10.Format? formatName,
    String? customPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateAiDeck, [], {
              #archetype: archetype,
              #strategy: strategy,
              #formatName: formatName,
              #customPrompt: customPrompt,
            }),
            returnValue: _i8.Future<_i5.DeckGeneration>.value(
              _FakeDeckGeneration_3(
                this,
                Invocation.method(#generateAiDeck, [], {
                  #archetype: archetype,
                  #strategy: strategy,
                  #formatName: formatName,
                  #customPrompt: customPrompt,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.DeckGeneration>.value(
              _FakeDeckGeneration_3(
                this,
                Invocation.method(#generateAiDeck, [], {
                  #archetype: archetype,
                  #strategy: strategy,
                  #formatName: formatName,
                  #customPrompt: customPrompt,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.DeckGeneration>);
}

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i13.CardRepository {
  @override
  String resolveCardImageUrl(String? fileName, {bool? cropped = false}) =>
      (super.noSuchMethod(
            Invocation.method(
              #resolveCardImageUrl,
              [fileName],
              {#cropped: cropped},
            ),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(
                #resolveCardImageUrl,
                [fileName],
                {#cropped: cropped},
              ),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(
                #resolveCardImageUrl,
                [fileName],
                {#cropped: cropped},
              ),
            ),
          )
          as String);

  @override
  _i8.Future<_i2.Page<_i6.Card>> fetchCards({
    String? query,
    String? type,
    String? attribute,
    String? race,
    String? archetype,
    int? page = 0,
    int? size = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCards, [], {
              #query: query,
              #type: type,
              #attribute: attribute,
              #race: race,
              #archetype: archetype,
              #page: page,
              #size: size,
            }),
            returnValue: _i8.Future<_i2.Page<_i6.Card>>.value(
              _FakePage_0<_i6.Card>(
                this,
                Invocation.method(#fetchCards, [], {
                  #query: query,
                  #type: type,
                  #attribute: attribute,
                  #race: race,
                  #archetype: archetype,
                  #page: page,
                  #size: size,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.Page<_i6.Card>>.value(
              _FakePage_0<_i6.Card>(
                this,
                Invocation.method(#fetchCards, [], {
                  #query: query,
                  #type: type,
                  #attribute: attribute,
                  #race: race,
                  #archetype: archetype,
                  #page: page,
                  #size: size,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.Page<_i6.Card>>);

  @override
  _i8.Future<_i6.Card> fetchCardDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCardDetail, [id]),
            returnValue: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#fetchCardDetail, [id])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#fetchCardDetail, [id])),
            ),
          )
          as _i8.Future<_i6.Card>);

  @override
  _i8.Future<List<String>> fetchMetadataValues(String? metadataPath) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMetadataValues, [metadataPath]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<_i6.Card> createCard(_i6.Card? card) =>
      (super.noSuchMethod(
            Invocation.method(#createCard, [card]),
            returnValue: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#createCard, [card])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#createCard, [card])),
            ),
          )
          as _i8.Future<_i6.Card>);

  @override
  _i8.Future<_i6.Card> updateCard(int? id, _i6.Card? card) =>
      (super.noSuchMethod(
            Invocation.method(#updateCard, [id, card]),
            returnValue: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#updateCard, [id, card])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.Card>.value(
              _FakeCard_4(this, Invocation.method(#updateCard, [id, card])),
            ),
          )
          as _i8.Future<_i6.Card>);

  @override
  _i8.Future<void> deleteCard(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCard, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
