package com.deck.lab.backend.dto.response;

import java.util.ArrayList;
import java.util.List;

import com.deck.lab.backend.dto.CardSuggestionDto;

/**
 * Data Transfer Object (DTO) wrapping the list of card suggestions generated by
 * the AI model.
 *
 * <p>
 * <strong>Response DTO</strong>
 * </p>
 * <p>
 * In REST API design, returning a raw top-level JSON array is discouraged
 * because it limits API extensibility and exposes applications to JSON
 * hijacking vulnerabilities. This class wraps the suggestion list in a single
 * object, allowing developers to add metadata fields (e.g. status, request
 * metrics) in the future without breaking existing clients.
 * </p>
 */
public class CardSuggestionsAiResponseDto {
    private List<CardSuggestionDto> suggestions = new ArrayList<>();

    public CardSuggestionsAiResponseDto() {
    }

    public CardSuggestionsAiResponseDto(List<CardSuggestionDto> suggestions) {
        this.suggestions = suggestions;
    }

    public List<CardSuggestionDto> getSuggestions() {
        return suggestions;
    }

    public void setSuggestions(List<CardSuggestionDto> suggestions) {
        this.suggestions = suggestions;
    }
}
