package com.deck.lab.backend.dto.response;

import java.util.ArrayList;
import java.util.List;

/**
 * Data Transfer Object (DTO) wrapping the list of card suggestions generated by the AI model.
 *
 * <p>
 * <strong>Response DTO</strong>
 * </p>
 * <p>
 * In REST API design, returning a raw top-level JSON array is discouraged because it limits API
 * extensibility and exposes applications to JSON hijacking vulnerabilities. This class wraps the
 * suggestion list in a single object, allowing developers to add metadata fields (e.g. status,
 * request metrics) in the future without breaking existing clients.
 * </p>
 */
public class CardSuggestionListResponseDto {
    private List<CardSuggestionResponseDto> suggestions = new ArrayList<>();

    public CardSuggestionListResponseDto() {
    }

    public CardSuggestionListResponseDto(List<CardSuggestionResponseDto> suggestions) {
        this.suggestions = suggestions;
    }

    public List<CardSuggestionResponseDto> getSuggestions() {
        return suggestions;
    }

    public void setSuggestions(List<CardSuggestionResponseDto> suggestions) {
        this.suggestions = suggestions;
    }
}
